project:
  type: website
  output-dir: docs

website:
  title: "My Personal Site"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: Final Year Project.qmd
        text: FYP 
      - href: travel.qmd
        text: Travel Experience
      - href: reflection.qmd
        text: Reflection on the use of GenAI

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-location: left

    



